#ifndef RELTT_LANG_MODS_HPP
        #define RELTT_LANG_MODS_HPP
        #include "Reltt.hpp"
Reltt_INT::QSRcModule Compilator();
Reltt_INT::QSRcModule CPP_Module();
Reltt_INT::QSRcModule Generator();
Reltt_INT::QSRcModule RelttSTD();
Reltt_INT::QSRcModule Remote();
Reltt_INT::QSRcModule Qemu_D();
#endif //RELTT_LANG_MODS_HPP