#ifndef RELTT_LANG_MODS_HPP
        #define RELTT_LANG_MODS_HPP
        #include "Reltt.hpp"
Reltt_INT::QSRcModule CPP_Module();
Reltt_INT::QSRcModule Qemu_D();
Reltt_INT::QSRcModule FSys();
Reltt_INT::QSRcModule Generator();
Reltt_INT::QSRcModule ASM();
Reltt_INT::QSRcModule RelttSTD();
Reltt_INT::QSRcModule Compilator();
#endif //RELTT_LANG_MODS_HPP